# railway.toml
[build]
  builder = "dockerfile"
  dockerfile = "DaineBot/Dockerfile"

[deploy]
  # Vous pouvez ajouter des variables d'environnement ici si nécessaire
  env = { "ASPNETCORE_ENVIRONMENT" = "Production" }