// <auto-generated />
using System;
using DaineBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaineBot.Migrations
{
    [DbContext(typeof(DaineBotDbContext))]
    [Migration("20250511181129_AddReadyCheckMessage")]
    partial class AddReadyCheckMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("DaineBot.Models.AdminRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Guild")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("RoleList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminRoles");
                });

            modelBuilder.Entity("DaineBot.Models.RaidSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hour")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minute")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NextSessionEditId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("RosterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NextSessionEditId");

                    b.HasIndex("RosterId");

                    b.ToTable("RaidSessions");
                });

            modelBuilder.Entity("DaineBot.Models.ReadyCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("AcceptedPlayers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Complete")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("DeniedPlayers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("ReadyChecks");
                });

            modelBuilder.Entity("DaineBot.Models.ReadyCheckMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CheckId");

                    b.ToTable("ReadyCheckMessages");
                });

            modelBuilder.Entity("DaineBot.Models.Roster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Guild")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RaidLeader")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RosterChannel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RosterRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rosters");
                });

            modelBuilder.Entity("DaineBot.Models.TmpRaidSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TmpSessions");
                });

            modelBuilder.Entity("DaineBot.Models.RaidSession", b =>
                {
                    b.HasOne("DaineBot.Models.RaidSession", "NextSessionEdit")
                        .WithMany()
                        .HasForeignKey("NextSessionEditId");

                    b.HasOne("DaineBot.Models.Roster", "Roster")
                        .WithMany("Sessions")
                        .HasForeignKey("RosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NextSessionEdit");

                    b.Navigation("Roster");
                });

            modelBuilder.Entity("DaineBot.Models.ReadyCheck", b =>
                {
                    b.HasOne("DaineBot.Models.RaidSession", "Session")
                        .WithOne("Check")
                        .HasForeignKey("DaineBot.Models.ReadyCheck", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DaineBot.Models.ReadyCheckMessage", b =>
                {
                    b.HasOne("DaineBot.Models.ReadyCheck", "Check")
                        .WithMany("Messages")
                        .HasForeignKey("CheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Check");
                });

            modelBuilder.Entity("DaineBot.Models.RaidSession", b =>
                {
                    b.Navigation("Check");
                });

            modelBuilder.Entity("DaineBot.Models.ReadyCheck", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DaineBot.Models.Roster", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
