// <auto-generated />
using System;
using DaineBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaineBot.Migrations
{
    [DbContext(typeof(DaineBotDbContext))]
    partial class DaineBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("DaineBot.Models.AdminRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Guild")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("RoleList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminRoles");
                });

            modelBuilder.Entity("DaineBot.Models.RaidSession", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RaidSessions");
                });

            modelBuilder.Entity("DaineBot.Models.ReadyCheck", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("AcceptedPlayers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("DeniedPlayers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReadyChecks");
                });

            modelBuilder.Entity("DaineBot.Models.Roster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Guild")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RosterChannel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RosterRole")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rosters");
                });

            modelBuilder.Entity("DaineBot.Models.RaidSession", b =>
                {
                    b.HasOne("DaineBot.Models.Roster", "Roster")
                        .WithMany("Sessions")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roster");
                });

            modelBuilder.Entity("DaineBot.Models.ReadyCheck", b =>
                {
                    b.HasOne("DaineBot.Models.RaidSession", "Session")
                        .WithOne("Check")
                        .HasForeignKey("DaineBot.Models.ReadyCheck", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DaineBot.Models.RaidSession", b =>
                {
                    b.Navigation("Check");
                });

            modelBuilder.Entity("DaineBot.Models.Roster", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
